// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SepeteEkleCikarTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sepeteEkleCikar() {
    driver.get("https://www.e-bebek.com/");
    driver.manage().window().setSize(new Dimension(1366, 728));
    driver.findElement(By.id("txtSearchBox")).sendKeys("biberon");
    driver.findElement(By.id("txtSearchBox")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".col-6:nth-child(1) .is-initialized > .ng-star-inserted")).click();
    driver.findElement(By.id("addToCartBtn")).click();
    driver.findElement(By.id("btnShowCart")).click();
    js.executeScript("window.scrollTo(0,18)");
    driver.findElement(By.cssSelector(".basket-product-item")).click();
    driver.findElement(By.id("iconRemoveProduct")).click();
    driver.findElement(By.cssSelector(".justify-content-center")).click();
    assertThat(driver.findElement(By.cssSelector("h2:nth-child(2)")).getText(), is("Sepetinizde ürün bulunmamaktadır."));
  }
}
